name: CAT API Tesning with Postman
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Newman and Export Test Results
        run: |
          newman run CAT-API.postman_collection.json --reporters json --reporter-json-export test_results.json

      - name: Upload Test Results to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -F 'payload_json={"content":"Test results file:"}' \
          -F 'file1=@test_results.json' \
          $DISCORD_WEBHOOK_URL

      - name: Send Discord Notification Test Passed
        if: always()
        env:
          DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1226464109680263219/cfAUULyxtqG79ydcUXW_5oeZKcFu6E7PeFiik8-b3R_GFjLVlnJOcU9Y8rClh0jgl5po
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"content":"Postman tests are completed!"}' $DISCORD_WEBHOOK_URL

      - name: Send Discord Notification Test Results
        if: always()
        env:
          DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1226464109680263219/cfAUULyxtqG79ydcUXW_5oeZKcFu6E7PeFiik8-b3R_GFjLVlnJOcU9Y8rClh0jgl5po
        run: |
          # Read test results from JSON file
          test_results=$(cat test_results.json)

          # Send test results to Discord
          curl -X POST -H 'Content-Type: application/json' --data-raw '{"content":"Test results:\n'"${test_results}"'"}' $DISCORD_WEBHOOK_URL
