name: CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Newman and htmlextra reporter
      run: |
        npm install -g newman@latest
        npm install -g newman-reporter-htmlextra

    - name: Run Postman Tests and Export HTML Report
      run: |
        newman run ./CAT-API.postman_collection.json --reporters htmlextra --reporter-htmlextra-export test_results.html

    - name: Upload Test Results to Discord
      if: always()
      env:
        DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1227220027183337524/THqo7lSXDCzLEDI3W8KeSNTGy2qNGGRpmciSlUf-Wj9EJsFv6kN8W7qDuZej0j5m2htS
      run: |
        Invoke-WebRequest -Uri $env:DISCORD_WEBHOOK_URL -Method Post -ContentType "multipart/form-data" -InFile "test_results.html" -Body @{content="Test results file"}
