name: REST-API Testing with Postman

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Newman and Export Test Results
        run: |
          newman run CAT-API.postman_collection.json --reporters htmlextra --reporter-htmlextra-export test_results.html

      - name: Upload Test Results to Discord
        if: always()
        env:
          DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1227220027183337524/THqo7lSXDCzLEDI3W8KeSNTGy2qNGGRpmciSlUf-Wj9EJsFv6kN8W7qDuZej0j5m2htS
        run: |
          curl -X POST -H 'Content-Type: multipart/form-data' \
          -F "file=@test_results.html" \
          -F "payload_json={\"content\":\"Test results file:\"}" \
          $DISCORD_WEBHOOK_URL

      - name: Send Discord Notification Test Passed
        if: always()
        env:
          DISCORD_WEBHOOK_URL: https://discordapp.com/api/webhooks/1227220027183337524/THqo7lSXDCzLEDI3W8KeSNTGy2qNGGRpmciSlUf-Wj9EJsFv6kN8W7qDuZej0j5m2htS
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"content":"Postman tests are completed!"}' $DISCORD_WEBHOOK_URL
