name: Node.js

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x] 
    
    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download Postman Collection
        run: curl -o collection.json https://url-to-your-postman-collection/collection.json




    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Newman
        run: newman run CAT-API.postman_collection.json

     
 
        
       
         
          
         
          
         

