name: Node.js

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Newman
        run: newman run catApi.json

      - name: Update Postman Collection
        run: |
         cp catApi.json path/to/CAT-API/
         git add catApi.json   
         git commit -m "Update Postman Collection"
         git push
 
        
       
         
          
         
          
         

